[package]
name = "ds-guizhou"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
log = "0.4"
ciborium = "0.2"
arrow-schema = { version = "55.1", features = ["serde"] }
mems = { path = "../.." }
csv = "1.3.0"
bytes = "1.10"
chrono = "0.4.38"
chrono-tz = "0.10"
